# Generated by Django 3.2.6 on 2023-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20230806_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='features',
            field=models.ManyToManyField(related_name='events', to='events.Feature'),
        ),
    ]
