# Generated by Django 4.2.11 on 2024-04-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
