# Generated by Django 4.2.11 on 2024-04-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_feature_subscriber_alter_category_options_and_more'),
        ('events', '0020_customuser_date_joined_customuser_email_and_more'),
    ]

    operations = [
    ]
