# Generated by Django 4.2.11 on 2024-04-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0023_customuser_user_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(db_table='events_customuser_groups', to='auth.group'),
        ),
    ]
