# Generated by Django 4.2.11 on 2024-04-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_userevent_event_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
