# Generated by Django 4.2.11 on 2024-04-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_event_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.review'),
        ),
    ]
